### ISSUE TITLE
Please remove the indentations

### ISSUE THREAD

**Issue by korenevskiy** [Chris2011/NetBeans-Breadcrumb-Explorer#12]
Please remove the indentation between the buttons and the indentation above and below the buttons.
Maybe there may be a problem that the path in the panel may not fit

**Comment by Chris2011** [comment]
Removing the padding will also not work for long paths and this is also not a problem, because you can scroll the whole panel horizontally. It was intended to have a JScrollPane around it. The padding is intended to be there, due to UX to have a bigger click area. Please test the scrolling yourself, by make NetBeans a bit smaller that the folders will not fit.

**Comment by korenevskiy** [comment]
When I hover the mouse. on the button, it is highlighted in the background. When hovering over the mouse, I call what is highlighted a button. And what is not highlighted and is an inactive area, I call an indentation. I'm asking you to remove the inactive area around the buttons. By reducing the panel and margins to the edges of the buttons.

**Comment by Chris2011** [comment]
Done in latest release: [1.4.0](https://github.com/Chris2011/NetBeans-Breadcrumb-Explorer/releases/tag/1.4.0)
